[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deezloadclone"
version = "2024.05.05"
description = "Downloads songs, albums or playlists from deezer and spotify (cloned from https://github.com/An0nimia/deezloader)"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "farihdzaky", email = "farihdzakyy@gmail.com" }
]
dependencies = [
    "mutagen>=*",
    "pycryptodome>=*",
    "requests>=*",
    "spotipy>=*",
    "tqdm>=*",
    "fastapi>=*",
    "uvicorn[standard]>=*",
    "librespot>=*"
]
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/farihdzkyy/deezloadclone"

[tool.setuptools]
packages = ["deezloader", "deezloader.models", "deezloader.spotloader", "deezloader.deezloader", "deezloader.libutils"]

[tool.setuptools.scripts]
deez-dw = "deezloader.bin.deez_dw:main"
deez-web = "deezloader.bin.deez_web:main"
